// AcroForm commands on the shared pdf.js backend.
import { YonderError } from '../errors'
import { fillFields, listFields, type FieldValue } from '../forms'
import { s } from '../schema'
import { requireDoc, type Command, type Outcome } from './context'

export const fields: Command = {
  name: 'forms.fields',
  group: 'forms',
  description: 'List form fields: name, type (text, checkbox, radio, combobox, listbox, signature), current value, export values / options, read-only and multi-select flags, page and box.',
  scope: 'both',
  needsDoc: true,
  produces: 'none',
  params: s.obj({}),
  examples: ['yonder-pdf forms.fields --in form.pdf --json'],
  async run(ctx): Promise<Outcome> {
    const list = await listFields(await requireDoc(ctx).pdfjs())
    return { result: { fields: list.map((f) => ({ ...f, page: f.page + 1 })) } }
  }
}

const decodeJson = (bytes: Uint8Array): unknown => {
  let text = ''
  for (let i = 0; i < bytes.length; i += 0x8000) text += String.fromCharCode.apply(null, Array.from(bytes.subarray(i, i + 0x8000)))
  try {
    return JSON.parse(decodeURIComponent(escape(text)))
  } catch {
    throw new YonderError('YP_INVALID_INPUT', 'values file is not valid JSON')
  }
}

export const fill: Command = {
  name: 'forms.fill',
  group: 'forms',
  description: 'Fill fields. --set name=value (repeatable; "true"/"false" or the export value for checkboxes, the export value for radios), --values as a JSON object {name: value}, or --values-file <file.json>. Values: string, boolean or string[] (multi-select listbox). Every assignment is validated before anything is written; appearances are generated by the same engine the app uses.',
  scope: 'both',
  needsDoc: true,
  produces: 'document',
  params: s.obj({
    set: s.arr(s.str('name=value'), 'Assignments'),
    values: s.record('Object of field values {name: value}'),
    valuesFile: s.str('JSON file with {name: value}'),
    flatten: s.bool('Also flatten the form after filling')
  }),
  examples: ['yonder-pdf forms.fill --in form.pdf --out filled.pdf --set name="Ada Lovelace" --set agree=true', 'yonder-pdf forms.fill --in form.pdf --out filled.pdf --values-file answers.json'],
  async run(ctx, p): Promise<Outcome> {
    const doc = requireDoc(ctx)
    const values: Record<string, FieldValue> = {}
    const absorb = (obj: unknown, source: string): void => {
      if (!obj || typeof obj !== 'object' || Array.isArray(obj)) throw new YonderError('YP_INVALID_INPUT', `${source} must be an object of {name: value}`)
      for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
        if (typeof v === 'string' || typeof v === 'boolean' || (Array.isArray(v) && v.every((x) => typeof x === 'string'))) values[k] = v as FieldValue
        else throw new YonderError('YP_INVALID_INPUT', `Value for "${k}" must be a string, boolean or list of strings`)
      }
    }
    if (p.valuesFile !== undefined) absorb(decodeJson(await ctx.readFile(String(p.valuesFile), 'json')), '--values-file')
    if (p.values !== undefined) absorb(p.values, '--values')
    for (const assignment of (p.set as string[] | undefined) ?? []) {
      const eq = assignment.indexOf('=')
      if (eq <= 0) throw new YonderError('YP_INVALID_INPUT', `--set expects name=value, got "${assignment}"`)
      const name = assignment.slice(0, eq)
      const v: FieldValue = assignment.slice(eq + 1) === 'true' ? true : assignment.slice(eq + 1) === 'false' ? false : assignment.slice(eq + 1)
      // The same name twice (--set list=a --set list=b) selects several options.
      const prev = values[name]
      values[name] = prev === undefined ? v : [...(Array.isArray(prev) ? prev : [String(prev)]), String(v)]
    }
    if (!Object.keys(values).length) throw new YonderError('YP_USAGE', 'Nothing to fill: give --set name=value, --values or --values-file')
    const pdf = await doc.pdfjs()
    const { bytes, applied } = await fillFields(pdf, values)
    await doc.replaceBytes(bytes)
    if (p.flatten) await doc.materialize({ flattenForms: true })
    return { result: { filled: applied, ...(p.flatten ? { flattenedForms: true } : {}) } }
  }
}

export const flattenForms: Command = {
  name: 'forms.flatten',
  group: 'forms',
  description: 'Flatten form fields into page content now (keeps current appearances; fields stop existing for every later operation and for the output).',
  scope: 'both',
  needsDoc: true,
  produces: 'document',
  params: s.obj({}),
  async run(ctx): Promise<Outcome> {
    await requireDoc(ctx).materialize({ flattenForms: true })
    return { result: { flattenedForms: true } }
  }
}

export const formsCommands: Command[] = [fields, fill, flattenForms]
