// AcroForm commands on the shared pdf.js backend.
import { YonderError } from '../errors'
import { fillFields, listFields, type FieldValue } from '../forms'
import { s } from '../schema'
import { requireDoc, type Command, type Outcome } from './context'

export const fields: Command = {
  name: 'forms.fields',
  group: 'forms',
  description: 'List form fields: name, type (text, checkbox, radio, combobox, listbox, signature), current value, export values / options, read-only flag, page and box.',
  scope: 'both',
  needsDoc: true,
  produces: 'none',
  params: s.obj({}),
  examples: ['yonder-pdf forms.fields --in form.pdf --json'],
  async run(ctx): Promise<Outcome> {
    const list = await listFields(await requireDoc(ctx).pdfjs())
    return { result: { fields: list.map((f) => ({ ...f, page: f.page + 1 })) } }
  }
}

export const fill: Command = {
  name: 'forms.fill',
  group: 'forms',
  description: 'Fill fields. --set name=value (repeatable; "true"/"false" or the export value for checkboxes, the export value for radios) or --values as a JSON object {name: value} where value is a string, boolean or string[] (listbox). Appearances are generated by the same engine the app uses.',
  scope: 'both',
  needsDoc: true,
  produces: 'document',
  params: s.obj({
    set: s.arr(s.str('name=value'), 'Assignments'),
    values: s.record('Object of field values {name: value}'),
    flatten: s.bool('Also flatten the form after filling')
  }),
  examples: ['yonder-pdf forms.fill --in form.pdf --out filled.pdf --set name="Ada Lovelace" --set agree=true'],
  async run(ctx, p): Promise<Outcome> {
    const doc = requireDoc(ctx)
    const values: Record<string, FieldValue> = {}
    if (p.values && typeof p.values === 'object') {
      for (const [k, v] of Object.entries(p.values as Record<string, unknown>)) {
        if (typeof v === 'string' || typeof v === 'boolean' || (Array.isArray(v) && v.every((x) => typeof x === 'string'))) values[k] = v as FieldValue
        else throw new YonderError('YP_INVALID_INPUT', `Value for "${k}" must be a string, boolean or list of strings`)
      }
    }
    for (const assignment of (p.set as string[] | undefined) ?? []) {
      const eq = assignment.indexOf('=')
      if (eq <= 0) throw new YonderError('YP_INVALID_INPUT', `--set expects name=value, got "${assignment}"`)
      const v = assignment.slice(eq + 1)
      values[assignment.slice(0, eq)] = v === 'true' ? true : v === 'false' ? false : v
    }
    if (!Object.keys(values).length) throw new YonderError('YP_USAGE', 'Nothing to fill: give --set name=value or --values')
    const pdf = await doc.pdfjs()
    const { bytes, applied } = await fillFields(pdf, values)
    await doc.replaceBytes(bytes)
    if (p.flatten) doc.commitOptions.flattenForms = true
    return { result: { filled: applied } }
  }
}

export const flattenForms: Command = {
  name: 'forms.flatten',
  group: 'forms',
  description: 'Flatten form fields into page content (keeps current appearances; fields stop being editable).',
  scope: 'both',
  needsDoc: true,
  produces: 'document',
  params: s.obj({}),
  async run(ctx): Promise<Outcome> {
    requireDoc(ctx).commitOptions.flattenForms = true
    return { result: { flattenForms: true } }
  }
}

export const formsCommands: Command[] = [fields, fill, flattenForms]
